### ISSUE TITLE
How to achieve transitions to predetermined shots?

### ISSUE THREAD

**Issue by JosephOhayon** [Animator-Anon/Animator#27]
Hi! First of all - this is just awesome. 
Congrats for making such a simple yet powerful way to animate SD. 

I am struggling with the seed command. I would like to force a specific seed only on one frame so I can get a specific predetermined shot, and then continue the animation from there. But it seems like no matter how I try to add the seed command, the animation just gets "stuck" as a result.

Am I misunderstanding the purpose of this command or how to use it? 
Is it possible to achieve a fluent animation from one predetermined shot to another predetermined (each with its own seed)? 

Would greatly appreciate any help. J

**Comment by Animator-Anon** [comment]
This is where it gets complicated. I don't know of a way to get the results you seek. I have been experimenting with a few things though.
One way was setting a seed for a specific time (If you want exact frame, you'll have to do the math) and set a high denoise strength for that time also. Then drop it down soon after before it trashes the image. This can force a strong generation of that seed.
Another thing I have been experimenting with seed marching (Others have been playing with this also), but the results are not amazing. In theory, you should be able to create a bunch of frames using txt2img, get everything how you want, then animate from one to the other. You'd set the seed for the current frame, subseed for the next frame and then vary the subseed strength from 0 to 1 to interpolate  between then. If you set a few seeds, and enable the seed march checkbox, the script will try and do this. You can look at the csv file to see how it ends up.
However it doesn't work perfectly. It doesn't seem to work well in img2img mode though, more a txt2img thing in that it generates a clean image from the prompts and seeds, rather than building on an existing image. However, in practice running it in txt2img mode, the resulting interpolated frames don't smoothly run into each other.
Maybe smarter people than me have figured it out.
